### PR TITLE
Chunked downloads

### PR DESCRIPTION
**Pull request by Anequit**
Let me know what you think

### CODE REVIEW

**Comment by izqalan** [comment]
tbh it still slow for me.

**Comment by izqalan** [comment]
It could be where I live. down speed on browser is around 50 KB/sec or around 3-4 mins for 10MB file.

**Comment by Anequit** [comment]
> It could be where I live. down speed on browser is around 50 KB/sec or around 3-4 mins for 10MB file.

for me I'm getting around 140 mbps and it's night and day for download speeds

**Comment by Anequit** [comment]
> It could be where I live. down speed on browser is around 50 KB/sec or around 3-4 mins for 10MB file.

it used to be stuck at using around 0.1-3mb but now it scales with your network, so the faster the internet is the faster it will download

**Comment by izqalan** [comment]
Fixed the test & I'm releasing this as Pre-release.

**Pull request merged**
